### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by ChetnaSingh23** [brijeshb42/kattappa#2]
KattapaEditor.js:177Uncaught TypeError: Cannot read property 'length' of undefined(…)render @

**Comment by ChetnaSingh23** [comment]
which node version are u using for this...

**Comment by brijeshb42** [comment]
I am using the latest node. It should work with version >= 4.x

**Comment by ChetnaSingh23** [comment]
okay....thanks... I'm using node 6.9.5
